apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blue-green-staging

resources:
  - ../../base

patches:
  - target:
      kind: Deployment
      name: myapp-green
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - target:
      kind: Service
      name: myapp-main-service
    patch: |-
      - op: replace
        path: /spec/selector/version
        value: "green"

images:
  - name: myapp-green
    newTag: "2.0-staging"