apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  config:
    log:
      mode: "console"
      level: "warn"
    auth:
      disable_login_form: false
      disable_signout_menu: true
  ingress:
    enabled: true
    path: /
    hosts:
      - grafana.local
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
