apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nodejs-servicemonitor
  labels:
    release: monitoring     #prometheus
spec:
  selector:
    matchLabels:
      app: nodejs-app
  namespaceSelector:
    matchNames:
      - default 
  endpoints:
    - port: http
      path: /metrics
      interval: 15s