apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-blue
  namespace: blue-green-demo
  labels:
    app: myapp
    version: blue
    environment: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
      version: blue
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: myapp
        version: blue
        environment: production
    spec:
      containers:
      - name: nginx
        image: ${REGISTRY_IP}:5000/myapp-blue:1.0
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 2
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-blue-service
  namespace: blue-green-demo
  labels:
    app: myapp
    version: blue
spec:
  selector:
    app: myapp
    version: blue
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP